spring:
  application:
    name: issue-service

  datasource:
    url: jdbc:postgresql://localhost:5432/sweflow
    username: sweflow
    password: sweflow
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    create-schemas: true
    default-schema: issue_schema
    schemas:
      - issue_schema

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: issue_schema

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: 8081
