name: sweflow

services:
  postgres:
    image: postgres:16
    container_name: sweflow-postgres
    environment:
      POSTGRES_DB: sweflow
      POSTGRES_USER: sweflow
      POSTGRES_PASSWORD: sweflow
    ports:
      - "5432:5432"
    volumes:
      - sweflow_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sweflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: sweflow-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: sweflow-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: sweflow-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sweflow-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: sweflow-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: sweflow-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: sweflow-kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: sweflow-zookeeper:2181
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sweflow-pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sweflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  minio:
    image: minio/minio
    container_name: sweflow-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: sweflow
      MINIO_ROOT_PASSWORD: sweflow123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  sweflow_postgres_data:
  redis-data:
  minio-data: