package com.sweflow.docagent.agents;

import com.sweflow.common.enums.ArtifactType;
import com.sweflow.common.events.ArtifactGeneratedEvent;
import com.sweflow.common.events.DocJobEvent;
import com.sweflow.docagent.producer.ArtifactEventProducer;
import com.sweflow.storage.ArtifactStorage;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;

@Slf4j
@Component
@RequiredArgsConstructor
public class DesignDocAgent {
    private final ArtifactEventProducer artifactEventProducer;
    private final ArtifactStorage artifactStorage;

    public void generate(DocJobEvent event) {
        try {
            String content = """
                    # Design Document

                    ## Issue

                    %s

                    ## Description

                    %s

                    ## Repository

                    %s

                    ## Proposed Solution

                    This is a mock design document generated by PRLens doc-agent.

                    ## Next Step

                    Trigger coding-agent to create a code change based on this design document.
                    """.formatted(
                    "Mock Title",
                    "Mock Description",
                    "Mock repository"
            );

            UUID artifactId = UUID.randomUUID();

            String objectKey = String.format(
                    "%s/%s/%s",
                    event.workflowId(),
                    ArtifactType.DESIGN_DOC.name(),
                    artifactId
            );

            artifactStorage.upload(
                    objectKey,
                    content.getBytes(StandardCharsets.UTF_8),
                    "text/markdown"
            );

            ArtifactGeneratedEvent artifactEvent = new ArtifactGeneratedEvent(
                    UUID.randomUUID(),
                    UUID.randomUUID(),
                    event.workflowId(),
                    event.workflowStepId(),
                    event.issueId(),
                    ArtifactType.DESIGN_DOC,
                    objectKey,
                    "doc-agent"
            );
            artifactEventProducer.publish(artifactEvent);
        } catch (Exception e) {
            log.error("Failed to design doc document. issueId = {}",
                    event.issueId(), e);
            throw new RuntimeException(e);
        }
    }

}
