spring:
  application:
    name: workflow-service

  datasource:
    url: jdbc:postgresql://localhost:5432/sweflow
    username: sweflow
    password: sweflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: workflow_schema

  flyway:
    enabled: true
    schemas: workflow_schema
    default-schema: workflow_schema
    create-schemas: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: workflow-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics